### ISSUE TITLE
How to Cite Cite PyMove in an academic paper?

### ISSUE THREAD

**Issue by YakshHaranwala** [InsightLab/PyMove#186]
I am along with other contributors, writing an evaluation of PyMove library in an academic paper and we want to cite the authors. Can you please help us with the citation?

**Comment by flych3r** [comment]
Hello. The library was originally created during the bachelor's thesis of 2 students from the Federal University of Ceará, so you can cite using both works.
```txt
@mastersthesis{arina2019,
	title        = {Uma Arquitetura E Implementação Do Módulo De Pré-processamento Para Biblioteca Pymove},
	author       = {Arina De Jesus Amador Monteiro Sanches},
	year         = 2019,
	school       = {Universidade Federal Do Ceará},
	type         = {Bachelor's thesis}
}
@mastersthesis{andreza2019,
	title        = {Uma Arquitetura E Implementação Do Módulo De Visualizaçãopara Biblioteca Pymove},
	author       = {Andreza Fernandes De Oliveira},
	year         = 2019,
	school       = {Universidade Federal Do Ceará},
	type         = {Bachelor's thesis}
}
```
We will add a citation section to the `README`, as well as some other work that led to new implementations added to PyMove when they are published.
When you finish and publish your paper, feel free to contact us again so that we can check it out too!

**Comment by YakshHaranwala** [comment]
Cited, Thanks a lot for your reply!
